# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
es:
 languageCode: es
 contentDir: content/es
 title: Lucas Rivero Iribarne
 params:
   description: Site description in Spanish...
 menu:
  main:
    - name: Inicio
      url: '#about'
      weight: 10
    - name: Experiencia
      url: '#experience'
      weight: 20
    # - name: Projects
    #   url: '#projects'
    #   weight: 30
    # - name: Talks
    #   url: '#talks'
    #   weight: 40
    - name: Publicaciones
      url: '#publications'
      weight: 50
    - name: Contacto
      url: '#contact'
      weight: 60

  # Link to a PDF of your resume/CV from the menu.
  # To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
    - name: CV
      url: uploads/resume.pdf
      weight: 70



